os: linux
dist: xenial
language: generic

services:
  - docker

before_install:
  - docker build -t bardioc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bardioc/docker-react npm run test -- --coverage