version: '3.7'

services: 
    web-dev:
        build: 
            context: '.'
            dockerfile: 'Dockerfile.dev'
        image: 'frontend-dev'
        ports: 
          - '3000:3000'
        volumes: 
          - '/app/node_modules'
          - '.:/app'
    web-test:
        image: 'frontend-test'
        volumes: 
          - '/app/node_modules'
          - '.:/app'
        command: [ 'npm', 'run', 'test' ]
    web-multi:
        build: 
            context: '.'
            dockerfile: 'Dockerfile.multi'
        image: 'frontend-prod'
        ports:
          - '5000:5000'
    

